<a href="https://colab.research.google.com/github/quotation3/TIL/blob/master/topic_modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import pandas as pd
import numpy as np
from sklearn.decomposition import randomized_svd

In [58]:
text = ['바나나 사과 포도 포도 짜장면',
        '사과 포도',
        '포도 바나나',
        '짜장면 짬뽕 탕수육',
        '볶음밥 탕수육',
        '짜장면 짬뽕',
        '라면 스시',
        '스시 짜장면',
        '가츠동 스시 소바',
        '된장찌개 김치찌개 김치',
        '김치 된장 짜장면',
        '비빔밥 김치']

In [59]:
text_word = []
for i in range(len(text)):
    text_word.append(text[i].split(' '))
text_word

[['바나나', '사과', '포도', '포도', '짜장면'],
 ['사과', '포도'],
 ['포도', '바나나'],
 ['짜장면', '짬뽕', '탕수육'],
 ['볶음밥', '탕수육'],
 ['짜장면', '짬뽕'],
 ['라면', '스시'],
 ['스시', '짜장면'],
 ['가츠동', '스시', '소바'],
 ['된장찌개', '김치찌개', '김치'],
 ['김치', '된장', '짜장면'],
 ['비빔밥', '김치']]

In [60]:
tokens = []

for i in range(len(text)):
    tokens.extend(text[i].split(' '))
tokens = list(set(tokens))

In [61]:
tdm = []

for i in range(len(text_word)):
    cnt_list = [0 for a in range(len(tokens))]
    for j in range(len(tokens)):
        if tokens[j] in text_word[i]:
            cnt_list[j] += text_word[i].count(tokens[j])
    tdm.append(cnt_list)
tdm

df=pd.DataFrame(tdm, index=text, columns=tokens)
df

짬뽕  된장  볶음밥  짜장면  가츠동  포도  ...  비빔밥  김치찌개  탕수육  라면  된장찌개  사과
바나나 사과 포도 포도 짜장면   0   0    0    1    0   2  ...    0     0    0   0     0   1
사과 포도              0   0    0    0    0   1  ...    0     0    0   0     0   1
포도 바나나             0   0    0    0    0   1  ...    0     0    0   0     0   0
짜장면 짬뽕 탕수육         1   0    0    1    0   0  ...    0     0    1   0     0   0
볶음밥 탕수육            0   0    1    0    0   0  ...    0     0    1   0     0   0
짜장면 짬뽕             1   0    0    1    0   0  ...    0     0    0   0     0   0
라면 스시              0   0    0    0    0   0  ...    0     0    0   1     0   0
스시 짜장면             0   0    0    1    0   0  ...    0     0    0   0     0   0
가츠동 스시 소바          0   0    0    0    1   0  ...    0     0    0   0     0   0
된장찌개 김치찌개 김치       0   0    0    0    0   0  ...    0     1    0   0     1   0
김치 된장 짜장면          0   1    0    1    0   0  ...    0     0    0   0     0   0
비빔밥 김치             0   0    0    0    0   0  ...    1     0    0   0     0   0

[12 rows x 16 columns]

In [62]:
U, s, VT = randomized_svd(np.array(tdm),
                              n_components=4,
                              n_iter=10,
                              random_state=None)

In [63]:
VT

array([[ 0.12448389,  0.0599366 ,  0.00783718,  0.48563449,  0.0082077 ,
         0.69686254,  0.0082077 ,  0.34843127,  0.06889362,  0.07739641,
         0.00823912,  0.00922069,  0.0736207 ,  0.00733397,  0.00922069,
         0.34843127],
       [ 0.3555557 ,  0.18480907,  0.04982669,  0.58415588,  0.06425309,
        -0.38741921,  0.06425309, -0.19370961,  0.25600828,  0.33700147,
         0.06761161,  0.0845808 ,  0.24835482,  0.05136218,  0.0845808 ,
        -0.19370961],
       [-0.10291629,  0.16197315, -0.02671012, -0.07468389, -0.22621639,
         0.03185185, -0.22621639,  0.01592593, -0.52268348,  0.61090353,
         0.18453253,  0.26439785, -0.0884251 , -0.15788435,  0.26439785,
         0.01592593],
       [-0.34945274,  0.06140467, -0.10775805, -0.18737521,  0.27669846,
         0.07489549,  0.27669846,  0.03744775,  0.55238845,  0.37136542,
         0.12393905,  0.1860217 , -0.3228814 ,  0.18435345,  0.1860217 ,
         0.03744775]])

In [64]:
vt = VT[:4, :]

In [65]:
vt

array([[ 0.12448389,  0.0599366 ,  0.00783718,  0.48563449,  0.0082077 ,
         0.69686254,  0.0082077 ,  0.34843127,  0.06889362,  0.07739641,
         0.00823912,  0.00922069,  0.0736207 ,  0.00733397,  0.00922069,
         0.34843127],
       [ 0.3555557 ,  0.18480907,  0.04982669,  0.58415588,  0.06425309,
        -0.38741921,  0.06425309, -0.19370961,  0.25600828,  0.33700147,
         0.06761161,  0.0845808 ,  0.24835482,  0.05136218,  0.0845808 ,
        -0.19370961],
       [-0.10291629,  0.16197315, -0.02671012, -0.07468389, -0.22621639,
         0.03185185, -0.22621639,  0.01592593, -0.52268348,  0.61090353,
         0.18453253,  0.26439785, -0.0884251 , -0.15788435,  0.26439785,
         0.01592593],
       [-0.34945274,  0.06140467, -0.10775805, -0.18737521,  0.27669846,
         0.07489549,  0.27669846,  0.03744775,  0.55238845,  0.37136542,
         0.12393905,  0.1860217 , -0.3228814 ,  0.18435345,  0.1860217 ,
         0.03744775]])

In [66]:
column_name = ['topic{}'.format(i+1) for i in range(4)]
df1 = pd.DataFrame(vt.T, index=tokens, columns=column_name)
df1

topic1    topic2    topic3    topic4
짬뽕    0.124484  0.355556 -0.102916 -0.349453
된장    0.059937  0.184809  0.161973  0.061405
볶음밥   0.007837  0.049827 -0.026710 -0.107758
짜장면   0.485634  0.584156 -0.074684 -0.187375
가츠동   0.008208  0.064253 -0.226216  0.276698
포도    0.696863 -0.387419  0.031852  0.074895
소바    0.008208  0.064253 -0.226216  0.276698
바나나   0.348431 -0.193710  0.015926  0.037448
스시    0.068894  0.256008 -0.522683  0.552388
김치    0.077396  0.337001  0.610904  0.371365
비빔밥   0.008239  0.067612  0.184533  0.123939
김치찌개  0.009221  0.084581  0.264398  0.186022
탕수육   0.073621  0.248355 -0.088425 -0.322881
라면    0.007334  0.051362 -0.157884  0.184353
된장찌개  0.009221  0.084581  0.264398  0.186022
사과    0.348431 -0.193710  0.015926  0.037448

In [67]:
topic_result = []
for name in column_name:
    topic_top = df1[name].sort_values(ascending=False)[0:3]
    topic_result.append(([topic_top.index, topic_top.values]))

topic_result

[[Index(['포도', '짜장면', '바나나'], dtype='object'),
  array([0.69686254, 0.48563449, 0.34843127])],
 [Index(['짜장면', '짬뽕', '김치'], dtype='object'),
  array([0.58415588, 0.3555557 , 0.33700147])],
 [Index(['김치', '된장찌개', '김치찌개'], dtype='object'),
  array([0.61090353, 0.26439785, 0.26439785])],
 [Index(['스시', '김치', '소바'], dtype='object'),
  array([0.55238845, 0.37136542, 0.27669846])]]

In [68]:
rank_by_topic =[]
for i in range(len(topic_result)):
    tmp = []
    for j in range(3):
        tmp.append([topic_result[i][0][j], topic_result[i][1][j]])
    rank_by_topic.append(tmp)
rank_by_topic

[[['포도', 0.6968625387988913],
  ['짜장면', 0.48563448882209015],
  ['바나나', 0.34843126939944563]],
 [['짜장면', 0.5841558837852067],
  ['짬뽕', 0.3555556968187592],
  ['김치', 0.3370014719129776]],
 [['김치', 0.6109035277294104],
  ['된장찌개', 0.2643978491951771],
  ['김치찌개', 0.2643978491951771]],
 [['스시', 0.5523884496346715],
  ['김치', 0.3713654174050597],
  ['소바', 0.2766984641841542]]]

In [69]:
for i in range(len(rank_by_topic)):
    print("{} - {}".format(column_name[i], rank_by_topic[i]))

topic1 - [['포도', 0.6968625387988913], ['짜장면', 0.48563448882209015], ['바나나', 0.34843126939944563]]
topic2 - [['짜장면', 0.5841558837852067], ['짬뽕', 0.3555556968187592], ['김치', 0.3370014719129776]]
topic3 - [['김치', 0.6109035277294104], ['된장찌개', 0.2643978491951771], ['김치찌개', 0.2643978491951771]]
topic4 - [['스시', 0.5523884496346715], ['김치', 0.3713654174050597], ['소바', 0.2766984641841542]]
