<a href="https://colab.research.google.com/github/quotation3/TIL/blob/master/XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [2]:
x = np.array([[0,0,1,1],[0,1,0,1]])
y = np.array([[0,1,1,0]])

In [6]:
h_num = 3
w1 = np.random.rand(2,h_num)
b1 = np.random.rand(h_num,1)
w2 = np.random.rand(h_num,1)
b2 = np.random.rand(1,1)

In [8]:
def sigmoid(X):
	return 1 / (1 + np.exp(-X))

In [9]:
def loss(y, y_hat):
    loss = -1 * 1/x.shape[1] * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

    return loss

In [15]:
epoch = 100000
learning_rate = 0.01
for epoch in range(epoch):

    # Hidden Node
    h = sigmoid(np.dot(w1.T, x) + b1)

    # y_hat
    y_hat = sigmoid(np.dot(w2.T, h) + b2)

    # Loss 계산
    loss = -1 * 1/x.shape[1] * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

    # BackPropagate: Hidden Layer
    dw2 = np.dot(h, (y_hat - y).T)
    db2 = 1 / y.shape[1] * np.sum(y_hat - y, axis = 1, keepdims = True)
    dh  = np.dot(w2, y_hat - y)

    # BackPropagate: Input Layer
    dz1 = dh * h * (1 - h)
    dw1 = np.dot(x, dz1.T)
    db1 = 1 / y.shape[1] * np.sum(dz1, axis = 1, keepdims = True)

    # Weight 수정
    w2 += -learning_rate * dw2
    b2 += -learning_rate * db2
    w1 += -learning_rate * dw1
    b1 += -learning_rate * db1

    if epoch % 10000 == 0:
        predict = y_hat
        print(predict)
        print(loss)

[[2.45596621e-04 9.94818049e-01 9.94838494e-01 7.49623656e-03]]
0.004535099372961817
[[2.10203300e-04 9.95367932e-01 9.95385216e-01 6.70263857e-03]]
0.004050930422678831
[[1.82826234e-04 9.95812406e-01 9.95827278e-01 6.06092995e-03]]
0.0036600135401161716
[[1.61112919e-04 9.96179104e-01 9.96192085e-01 5.53133792e-03]]
0.0033378038646458136
[[1.43532813e-04 9.96486785e-01 9.96498251e-01 5.08685426e-03]]
0.0030676687799435134
[[1.29051075e-04 9.96748625e-01 9.96758854e-01 4.70849698e-03]]
0.0028379394020569414
[[1.16945166e-04 9.96974154e-01 9.96983358e-01 4.38253609e-03]]
0.0026401885074607704
[[1.06696652e-04 9.97170431e-01 9.97178773e-01 4.09879530e-03]]
0.002468178550460953
[[9.79247415e-05 9.97342798e-01 9.97350409e-01 3.84957250e-03]]
0.002317194206021093
[[9.03439950e-05 9.97495372e-01 9.97502354e-01 3.62893114e-03]]
0.002183604931494064


### Class화 하기

In [46]:
class XOR:
    def __init__ (self, x, y):
        self.x=x
        self.y=y
        self.w1=[]
        self.b1=[]
        self.w2=[]
        self.b2=[]

    def create_weight(self,h_num):
        self.w1 = np.random.rand(2,h_num)
        self.b1 = np.random.rand(h_num,1)
        self.w2 = np.random.rand(h_num,1)
        self.b2 = np.random.rand(1,1)
    
    def optimize(self,epoch,learning_rate):
        for epoch in range(epoch):
           h = sigmoid(np.dot(self.w1.T, self.x) + self.b1)
           y_hat = sigmoid(np.dot(self.w2.T, h) + self.b2)
           loss = -1 * 1/self.x.shape[1] * np.sum(self.y * np.log(y_hat) + (1 - self.y) * np.log(1 - y_hat))

           if epoch % 10000 == 0:
               predict = y_hat
               print('반복횟수: {}, 예측값: {}, Loss: {}'.format(epoch,predict,loss))
           
           dw2 = np.dot(h, (y_hat - self.y).T)
           db2 = 1 / self.y.shape[1] * np.sum(y_hat - self.y, axis = 1, keepdims = True)
           dh  = np.dot(self.w2, y_hat - self.y)
           
           dz1 = dh * h * (1 - h)
           dw1 = np.dot(self.x, dz1.T)
           db1 = 1 / self.y.shape[1] * np.sum(dz1, axis = 1, keepdims = True)
           
           self.w2 += -learning_rate * dw2
           self.b2 += -learning_rate * db2
           self.w1 += -learning_rate * dw1
           self.b1 += -learning_rate * db1

In [47]:
xor=XOR(x,y)

In [48]:
xor.create_weight(3)

In [49]:
xor.optimize(100000,0.01)

반복횟수: 0, 예측값: [[0.81937977 0.83187739 0.83731008 0.84662164]], Loss: 0.986959282901829
반복횟수: 10000, 예측값: [[0.48868513 0.43235982 0.58648215 0.47739757]], Loss: 0.6729535388715977
반복횟수: 20000, 예측값: [[0.0160117  0.92314731 0.93291758 0.09816783]], Loss: 0.06721824660921609
반복횟수: 30000, 예측값: [[0.00326778 0.97187346 0.97318202 0.03876725]], Loss: 0.024631414493819316
반복횟수: 40000, 예측값: [[0.00150972 0.98288079 0.98339912 0.0240061 ]], Loss: 0.014954368040693862
반복횟수: 50000, 예측값: [[9.10192769e-04 9.87706747e-01 9.87994284e-01 1.73731519e-02]], Loss: 0.01072106253547858
반복횟수: 60000, 예측값: [[6.25673028e-04 9.90412506e-01 9.90599793e-01 1.36105552e-02]], Loss: 0.008352078547528164
반복횟수: 70000, 예측값: [[4.64928994e-04 9.92142679e-01 9.92276581e-01 1.11877634e-02]], Loss: 0.006839401476887202
반복횟수: 80000, 예측값: [[3.63732006e-04 9.93344018e-01 9.93445734e-01 9.49759248e-03]], Loss: 0.005790213181412444
반복횟수: 90000, 예측값: [[2.95139790e-04 9.94226736e-01 9.94307354e-01 8.25145334e-03]], Loss: 0.0050199432